### PR TITLE
dropdown gene symbols now match data file

### PR DESCRIPTION
**Pull request by Graeme-Smith**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/coverage_boxplots/4)

### CODE REVIEW

**Comment by Graeme-Smith** [comment]
___
*[CovApp/App.R, line 11 at r2](https://reviewable.io/reviews/moka-guys/coverage_boxplots/4#-LOxEqBj0EoUmklMEyKj:-LOxEqBkEhcBUMf-yd37:bm0i7eb) ([raw file](https://github.com/moka-guys/coverage_boxplots/blob/657da2d9aaad20a916f44ebc81bd3eee1f944ca6/CovApp/App.R#L11)):*
> ```
> # load files, files must be in the same directory as App.R script
> # List of genes for user selection
> genelist <- read_tsv("CovGeneSymbOct2018.txt")
> ```

I changed this line so that it imports the latest list of gene symbols + tested my local instance against shinyapps.io version

**Comment by Graeme-Smith** [comment]
___
*[CovApp/CovGeneSymbOct2018.txt, line 0 at r1](https://reviewable.io/reviews/moka-guys/coverage_boxplots/4#-LOx8wre-JhXDjsenKgr:-LOx8wrf2oSLq50KlP5R:bvwe3td) ([raw file](https://github.com/moka-guys/coverage_boxplots/blob/2865f6c279d45fb32c76c2b284f0d8cab070320c/CovApp/CovGeneSymbOct2018.txt#L0)):*
I created this new file from covtidy.tx using the code below in response to issue #316:

covtidy <- read_tsv("covtidy.txt")
#Extract unique gene names from data and sort alphabetically
new_gene_list <- sort(unique(covtidy$Gene))
#Convert from list to dataframe ready for writing to file
new_gene_list <- as.data.frame(new_gene_list)
#Add column name so that written file will resemble the original format
colnames(new_gene_list) <- "Genesymbol"
#Save new table
write.table(new_gene_list, file='CovGeneSymbOct2018.txt', quote=FALSE, sep='\t', row.names = FALSE)

**Review by aledj2 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/coverage_boxplots/4)* status: all files reviewed, 2 unresolved discussions

**Review by aledj2 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/coverage_boxplots/4#-:-LOxf8I89JD8QZ0oI_v-:bg7igkv)* status: all files reviewed, 2 unresolved discussions

**Review by aledj2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/coverage_boxplots/4)* status: all files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith)

**Comment by Graeme-Smith** [comment]
:lgtm:

**Pull request merged**
